version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    reviewers:
      - bdhoine
      - royteeuwen
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "io.wcm.maven:io.wcm.maven.aem-dependencies"
        versions: [ "[6.5.17,)" ]
      - dependency-name: "biz.aQute.bnd:bnd-maven-plugin"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "org.apache.commons:commons-csv"
        versions: [ "[1.10.0,)" ]
  - package-ecosystem: "npm"
    directory: "/ui.tests"
    reviewers:
      - bdhoine
      - royteeuwen
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - bdhoine
      - royteeuwen
    schedule:
      interval: "weekly"