name: Build

on: [ push, pull_request ]

jobs:
  aem-maven-build:
    uses: orbinson/workflows/.github/workflows/aem-maven-build.yml@main
    with:
      java-version: 11

  ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest
    needs: aem-maven-build
    services:
      aem-author:
        image: ghcr.io/orbinson/aem-sdk:author-2024.10.18459.20241031T210302Z-241000
        ports:
          - 4502:4502
        volumes:
          - /logs:/opt/aem/home/var/instance/author/crx-quickstart/logs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
          cache: maven
      - name: Get Playwright version from package-lock.json
        run: echo "PLAYWRIGHT_VERSION=$(jq -r '.packages["node_modules/playwright-core"].version' ui.tests/package-lock.json)" >> $GITHUB_ENV
      - name: Cache Playwright binaries
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install package
        run: mvn install -B -U -PautoInstallSinglePackage
      - name: Install it.content
        run: mvn install -B -U -PautoInstallPackage -pl it.content
      - name: Run ui.tests
        run: mvn test -B -pl ui.tests -DskipTests=false
      - name: "Upload Playwright Report"
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ui.tests/playwright-report/
      - name: "Upload AEM logs"
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: logs
          path: /logs
